name: CI/CD Pipeline

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: METAPHORCE
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 20
      uses: actions/setup-java@v3
      with:
        java-version: '20'
        distribution: 'temurin'

    - name: Build project
      run: mvn clean package -DskipTests

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Build Docker image
      run: docker build -t ${{ secrets.DOCKER_USERNAME }}/web_server_app .

    - name: Push Docker image
      run: docker push ${{ secrets.DOCKER_USERNAME }}/web_server_app
